### ISSUE TITLE
DWCNet

### ISSUE THREAD

**Issue by oceanzhf** [781458112/DWWA#1]
请问关于DWCNet的代码在哪个文件里呀

**Comment by 781458112** [comment]
此代码是基于mmdetection修改的，有关DWCNet部分在mmdet/backbone/my_detectors_resnet.py中

**Comment by oceanzhf** [comment]
怎么感觉看这个代码跟您论文里的小波神经网络的图对不上呀，在您的图里只用了三个卷积，代码看着要复杂很多。

**Comment by 781458112** [comment]
主体是论文中所绘制的结构，代码更为复杂是因为要把输入输出对应所以加了部分代码。

**Comment by oceanzhf** [comment]
> 主体是论文中所绘制的结构，代码更为复杂是因为要把输入输出对应所以加了部分代码。

您好，我在您说的文件里并没有看见您提出的小波神经网络的细节，只有DWWA-Net，请问小波神经网络是在哪个文件

**Comment by 781458112** [comment]
具体就在my_detectors_resnet.py中

**Comment by lxm-101** [comment]
您好，在哪里可以下载预训练权重

**Comment by 781458112** [comment]
@lxm-101 请参考issues，里面有提这个问题且我们将预训练权重进行了上传
