### ISSUE TITLE
I have observed a discrepancy in the comparative experiments on the NEU-DET dataset as presented in your paper, contrasting with the results reported in the referenced literature.

### ISSUE THREAD

**Issue by HHX-688** [781458112/DWWA#6]
I have observed a discrepancy in the comparative experiments on the NEU-DET dataset as presented in your paper, contrasting with the results reported in the referenced literature. For instance, the twenty-first referenced paper reports a mean Average Precision (mAP) of 82.3% on the NEU-DET dataset. However, in your attempt to replicate the experiment, you achieved a mAP result of 72.0%. Since the code from the referenced paper is not publicly disclosed, could you please clarify the methodology you employed for conducting the comparative experiments?

**Comment by 781458112** [comment]
In fact, since the NEU dataset does not give a clear distribution of the training and test sets, we used a random selection of the training and test datasets. In addition, we reproduce the code of Ref. and validate it using the NEU dataset.
